### ISSUE TITLE
UnitTest failure

### ISSUE THREAD

**Issue by sneumann** [glibiseller/IPO#7]
Hi, one value in the unit tests seems to have slightly changed,
most likely requires just updating the expected value or tolerance.

````
Running the tests in ‘tests/runTests.R’ failed.
Last 13 lines of output:
  IPO RUnit Tests - 1 test function, 0 errors, 1 failure
  FAILURE in test_ipo: Error in checkEqualsNumeric(unlist(TV)[4], 0.0006312929, tolerance = 1e-06) : 
    Mean relative difference: 0.006195529
````

**Comment by glibiseller** [comment]
Hi!

The unit test finished without an error on my windows machine:
* R version 3.1.1 (2014-07-10)
* Platform: i386-w64-mingw32/i386 (32-bit)
* IPO 1.6.2 
* xcms_1.42.0

but does not on linux:
* R version 3.0.0 (2013-04-03)
* Platform: x86_64-pc-linux-gnu (64-bit)
* IPO 1.6
* xcms_1.42.0

Changing the tolerance to 1e-03 would solve the problem on the linux machine.

Maybe its due to 32 and 64 bit enviroments. What do you think?

**Comment by sneumann** [comment]
increase tolerance would be fine with me, if that's what one can expect 
across platforms.

**Comment by glibiseller** [comment]
I updated the tolerance. Now the tests work fine on 32 and 64 bit.
